# Auto-labeling configuration for PRs

# Documentation
documentation:
  - '**/*.md'
  - 'docs/**/*'

# Tests
tests:
  - 'tests/**/*'
  - '**/*Tests.cs'
  - '**/*Test.cs'

# Building Blocks
building-blocks:
  - 'src/building-blocks/**/*'

# Services
auth:
  - 'src/services/AcademyIODevops.Auth.API/**/*'

courses:
  - 'src/services/AcademyIODevops.Courses.API/**/*'

payments:
  - 'src/services/AcademyIODevops.Payments.API/**/*'

students:
  - 'src/services/AcademyIODevops.Students.API/**/*'

# BFF
bff:
  - 'src/api-gateways/AcademyIODevops.Bff/**/*'

# Infrastructure
infrastructure:
  - 'docker-compose*.yml'
  - 'Dockerfile*'
  - '.github/**/*'

# Database
database:
  - '**/Migrations/**/*'
  - '**/Data/**/*'

# Configuration
configuration:
  - 'appsettings*.json'
  - '**/*.config'
